import { GrowthPartnerProfile } from './types';

export const mockGrowthPartners: GrowthPartnerProfile[] = [
  {
    partnerId: 'GP-101',
    name: 'Kunal Singhania',
    phone: '+91 98201 44892',
    email: 'kunal.singhania@apexluxury.in',
    tier: 'Diamond',
    joinedDate: '2026-08-15',
    region: 'Mumbai & Western Coast Elite Sector',
    totalShopsOnboarded: 14,
    verifiedShops: 12,
    qualifyingShops: 10,
    shopsCompleting15DayCycle: 9,
    rejectedShops: 1,
    currentMilestone: 'Tier-3 Diamond Partner (10+ Salons Qualifying)',
    nextMilestone: 'Apex Sovereign Partner (15 Salons Completing 15-Day Cycle)',
    remainingShopsForNextMilestone: 1,
    plusOneShopStatus: 'Plus-One (+1) Shop "Silk & Ivory UB City" on Day 14/15 (Matures in 24 Hours)',
    currentEligibleReward: 'Nexora 24K Pure Gold Executive Desk Emblem (100g) + ₹1,50,000 Cash Grant',
    claimStatus: 'Eligible to Claim',
    shops: [
      {
        shopId: 'NX-SHP-001',
        shopName: "L'Étoile Hair Lounge (Main Flagship)",
        ownerName: 'Master Jean-Jacques',
        mobileNumber: '+91 98200 99124',
        address: 'Villa 14, Waterfield Road, Bandra West',
        city: 'Mumbai',
        kycStatus: 'Verified',
        qrActivationDate: '2026-08-18',
        dailyQrTransaction: 18500,
        requiredDailyQrTransaction: 1000,
        companyCommissionRate: 10,
        dailyCompanyCommission: 1850,
        dailyQualification: 'Passed',
        consecutiveQualifyingDays: 15,
        isCycleCompleted: true,
        settlementStatus: 'Settled (Bank UTR Released)',
        refundReversalStatus: 'Zero Reversals (Clean)',
        verificationStatus: 'Verified & Active',
        interiorPhoto: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&q=80&w=600',
        category: 'High-Fashion Hair Couture',
      },
      {
        shopId: 'NX-SHP-002',
        shopName: 'AURA Luxury Thermal Spa',
        ownerName: 'Dr. Kabir Sethi',
        mobileNumber: '+91 98111 88392',
        address: 'Sanctuary Pavilion, Basant Lok, Vasant Vihar',
        city: 'New Delhi',
        kycStatus: 'Verified',
        qrActivationDate: '2026-08-20',
        dailyQrTransaction: 22000,
        requiredDailyQrTransaction: 1000,
        companyCommissionRate: 10,
        dailyCompanyCommission: 2200,
        dailyQualification: 'Passed',
        consecutiveQualifyingDays: 15,
        isCycleCompleted: true,
        settlementStatus: 'Settled (Bank UTR Released)',
        refundReversalStatus: 'Zero Reversals (Clean)',
        verificationStatus: 'Verified & Active',
        interiorPhoto: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=600',
        category: 'Thermal Spa & Aesthetics',
      },
      {
        shopId: 'NX-SHP-003',
        shopName: 'Silk & Ivory Couture Nails',
        ownerName: 'Devika Krishnan',
        mobileNumber: '+91 97400 66210',
        address: 'Level 2, The Collection, UB City Mall',
        city: 'Bengaluru',
        kycStatus: 'Verified',
        qrActivationDate: '2026-09-14',
        dailyQrTransaction: 1250,
        requiredDailyQrTransaction: 1000,
        companyCommissionRate: 10,
        dailyCompanyCommission: 125,
        dailyQualification: 'Passed',
        consecutiveQualifyingDays: 14,
        isCycleCompleted: false,
        settlementStatus: 'In Escrow (Rolling 15-Day)',
        refundReversalStatus: 'Zero Reversals (Clean)',
        verificationStatus: 'Verified & Active',
        interiorPhoto: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&q=80&w=600',
        category: 'Couture Nail Art & Spa',
      },
      {
        shopId: 'NX-SHP-004',
        shopName: 'The Obsidian Ink Atelier',
        ownerName: 'Sven Lindqvist',
        mobileNumber: '+91 94140 33819',
        address: 'Plot 8, Shivaji Marg, C-Scheme',
        city: 'Jaipur',
        kycStatus: 'Verified',
        qrActivationDate: '2026-08-25',
        dailyQrTransaction: 25000,
        requiredDailyQrTransaction: 1000,
        companyCommissionRate: 10,
        dailyCompanyCommission: 2500,
        dailyQualification: 'Passed',
        consecutiveQualifyingDays: 15,
        isCycleCompleted: true,
        settlementStatus: 'Settled (Bank UTR Released)',
        refundReversalStatus: 'Zero Reversals (Clean)',
        verificationStatus: 'Verified & Active',
        interiorPhoto: 'https://images.unsplash.com/photo-1598256989800-fe5f95da9787?auto=format&fit=crop&q=80&w=600',
        category: 'Bespoke Ink & Jewelry',
      },
      {
        shopId: 'NX-SHP-005',
        shopName: 'Maison Noir Grooming Club',
        ownerName: 'Ranveer Singhania',
        mobileNumber: '+91 98203 11844',
        address: 'Chambers 4, High Street Phoenix, Lower Parel',
        city: 'Mumbai',
        kycStatus: 'Verified',
        qrActivationDate: '2026-09-01',
        dailyQrTransaction: 9200,
        requiredDailyQrTransaction: 1000,
        companyCommissionRate: 10,
        dailyCompanyCommission: 920,
        dailyQualification: 'Passed',
        consecutiveQualifyingDays: 15,
        isCycleCompleted: true,
        settlementStatus: 'Settled (Bank UTR Released)',
        refundReversalStatus: 'Zero Reversals (Clean)',
        verificationStatus: 'Verified & Active',
        interiorPhoto: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&q=80&w=600',
        category: 'Men Haute Grooming',
      },
      {
        shopId: 'NX-SHP-006',
        shopName: 'Amber & Pearl Bridal Sanctuary',
        ownerName: 'Simran Bajaj',
        mobileNumber: '+91 98118 77209',
        address: 'Boutique Row, Greater Kailash 2 M-Block',
        city: 'New Delhi',
        kycStatus: 'Verified',
        qrActivationDate: '2026-09-04',
        dailyQrTransaction: 16400,
        requiredDailyQrTransaction: 1000,
        companyCommissionRate: 10,
        dailyCompanyCommission: 1640,
        dailyQualification: 'Passed',
        consecutiveQualifyingDays: 15,
        isCycleCompleted: true,
        settlementStatus: 'Settled (Bank UTR Released)',
        refundReversalStatus: 'Zero Reversals (Clean)',
        verificationStatus: 'Verified & Active',
        interiorPhoto: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=600',
        category: 'Bridal Couture Artistry',
      },
      {
        shopId: 'NX-SHP-007',
        shopName: 'Velvet Crown Hair Spa',
        ownerName: 'Aarav Merchant',
        mobileNumber: '+91 98205 33419',
        address: 'Clover Park, North Main Road, Koregaon Park',
        city: 'Pune',
        kycStatus: 'Verified',
        qrActivationDate: '2026-09-10',
        dailyQrTransaction: 800,
        requiredDailyQrTransaction: 1000,
        companyCommissionRate: 10,
        dailyCompanyCommission: 80,
        dailyQualification: 'Not Passed',
        consecutiveQualifyingDays: 8,
        isCycleCompleted: false,
        settlementStatus: 'In Escrow (Rolling 15-Day)',
        refundReversalStatus: 'Zero Reversals (Clean)',
        verificationStatus: 'Verified & Active',
        interiorPhoto: 'https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&q=80&w=600',
        category: 'Trichology & Hair Spa',
      },
      {
        shopId: 'NX-SHP-008',
        shopName: 'Opulence Skin Alchemi',
        ownerName: 'Dr. Natasha Verma',
        mobileNumber: '+91 98109 44102',
        address: 'Sector 54, Golf Course Road',
        city: 'Gurugram',
        kycStatus: 'Verified',
        qrActivationDate: '2026-09-05',
        dailyQrTransaction: 14500,
        requiredDailyQrTransaction: 1000,
        companyCommissionRate: 10,
        dailyCompanyCommission: 1450,
        dailyQualification: 'Passed',
        consecutiveQualifyingDays: 15,
        isCycleCompleted: true,
        settlementStatus: 'Settled (Bank UTR Released)',
        refundReversalStatus: 'Zero Reversals (Clean)',
        verificationStatus: 'Verified & Active',
        interiorPhoto: 'https://images.unsplash.com/photo-1519415510236-718bdfcd89c8?auto=format&fit=crop&q=80&w=600',
        category: 'Clinical Skin Aesthetics',
      },
      {
        shopId: 'NX-SHP-009',
        shopName: 'Zephyr Beachside Wellness Spa',
        ownerName: 'Carlos Dsouza',
        mobileNumber: '+91 98221 66890',
        address: 'De Mello Vaddo, Assagao',
        city: 'Goa',
        kycStatus: 'Verified',
        qrActivationDate: '2026-09-08',
        dailyQrTransaction: 11200,
        requiredDailyQrTransaction: 1000,
        companyCommissionRate: 10,
        dailyCompanyCommission: 1120,
        dailyQualification: 'Passed',
        consecutiveQualifyingDays: 15,
        isCycleCompleted: true,
        settlementStatus: 'Settled (Bank UTR Released)',
        refundReversalStatus: 'Zero Reversals (Clean)',
        verificationStatus: 'Verified & Active',
        interiorPhoto: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&q=80&w=600',
        category: 'Ayurvedic & Luxury Spa',
      },
      {
        shopId: 'NX-SHP-010',
        shopName: 'Lumiere Face & Brow Studio',
        ownerName: 'Tanya Kapoor',
        mobileNumber: '+91 98207 88901',
        address: 'Juhu Tara Road, Opp Soho House',
        city: 'Mumbai',
        kycStatus: 'Verified',
        qrActivationDate: '2026-09-12',
        dailyQrTransaction: 6500,
        requiredDailyQrTransaction: 1000,
        companyCommissionRate: 10,
        dailyCompanyCommission: 650,
        dailyQualification: 'Passed',
        consecutiveQualifyingDays: 15,
        isCycleCompleted: true,
        settlementStatus: 'Settled (Bank UTR Released)',
        refundReversalStatus: 'Zero Reversals (Clean)',
        verificationStatus: 'Verified & Active',
        interiorPhoto: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&q=80&w=600',
        category: 'Micro-pigmentation Studio',
      },
      {
        shopId: 'NX-SHP-011',
        shopName: 'Regal Mane Traditional Barbershop',
        ownerName: 'Vikram Joshi',
        mobileNumber: '+91 97401 55219',
        address: '100ft Road, HAL 2nd Stage, Indiranagar',
        city: 'Bengaluru',
        kycStatus: 'Verified',
        qrActivationDate: '2026-09-15',
        dailyQrTransaction: 750,
        requiredDailyQrTransaction: 1000,
        companyCommissionRate: 10,
        dailyCompanyCommission: 75,
        dailyQualification: 'Not Passed',
        consecutiveQualifyingDays: 5,
        isCycleCompleted: false,
        settlementStatus: 'In Escrow (Rolling 15-Day)',
        refundReversalStatus: 'Zero Reversals (Clean)',
        verificationStatus: 'Verified & Active',
        interiorPhoto: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?auto=format&fit=crop&q=80&w=600',
        category: 'Luxury Barbering',
      },
      {
        shopId: 'NX-SHP-012',
        shopName: 'Elysian Aesthetic Clinic',
        ownerName: 'Dr. Siddharth Mallya',
        mobileNumber: '+91 98200 44199',
        address: 'Altamount Road, Cumballa Hill',
        city: 'Mumbai',
        kycStatus: 'Verified',
        qrActivationDate: '2026-09-18',
        dailyQrTransaction: 31000,
        requiredDailyQrTransaction: 1000,
        companyCommissionRate: 10,
        dailyCompanyCommission: 3100,
        dailyQualification: 'Passed',
        consecutiveQualifyingDays: 10,
        isCycleCompleted: false,
        settlementStatus: 'In Escrow (Rolling 15-Day)',
        refundReversalStatus: 'Zero Reversals (Clean)',
        verificationStatus: 'Verified & Active',
        interiorPhoto: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&q=80&w=600',
        category: 'Laser & Aesthetic Dermatology',
      },
      {
        shopId: 'NX-SHP-013',
        shopName: 'Chrono Cutters Urban Lounge',
        ownerName: 'Rohit Khandelwal',
        mobileNumber: '+91 94140 77122',
        address: 'Tonk Road, Bapu Nagar',
        city: 'Jaipur',
        kycStatus: 'Pending',
        qrActivationDate: '2026-09-22',
        dailyQrTransaction: 0,
        requiredDailyQrTransaction: 1000,
        companyCommissionRate: 10,
        dailyCompanyCommission: 0,
        dailyQualification: 'Not Passed',
        consecutiveQualifyingDays: 0,
        isCycleCompleted: false,
        settlementStatus: 'Pending Verification',
        refundReversalStatus: 'None',
        verificationStatus: 'Under Inspection',
        interiorPhoto: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&q=80&w=600',
        category: 'Contemporary Hair Art',
      },
      {
        shopId: 'NX-SHP-014',
        shopName: 'Elite Unisex Parlour (Malad Hub)',
        ownerName: 'Rameshwar Pal',
        mobileNumber: '+91 98209 00192',
        address: 'Station Road, Malad West',
        city: 'Mumbai',
        kycStatus: 'Rejected',
        qrActivationDate: 'N/A (Activation Denied)',
        dailyQrTransaction: 0,
        requiredDailyQrTransaction: 1000,
        companyCommissionRate: 10,
        dailyCompanyCommission: 0,
        dailyQualification: 'Not Passed',
        consecutiveQualifyingDays: 0,
        isCycleCompleted: false,
        settlementStatus: 'Hold (Anomaly)',
        refundReversalStatus: 'None',
        verificationStatus: 'Rejected',
        rejectionReason: 'Aesthetic standard criteria failed: Space does not meet Nexora luxury 4-bay minimum luxury interior architecture, no autoclave sterilization documentation, and low-grade cosmetic products detected.',
        interiorPhoto: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=600',
        category: 'Unisex Parlour',
      },
    ],
  },
  {
    partnerId: 'GP-102',
    name: 'Meera Rajput',
    phone: '+91 98110 52319',
    email: 'meera.rajput@delhistyle.com',
    tier: 'Platinum',
    joinedDate: '2026-08-28',
    region: 'North India & NCR Luxury Belt',
    totalShopsOnboarded: 9,
    verifiedShops: 8,
    qualifyingShops: 7,
    shopsCompleting15DayCycle: 6,
    rejectedShops: 1,
    currentMilestone: 'Tier-2 Platinum Partner (5+ Salons Qualifying)',
    nextMilestone: 'Tier-3 Diamond Partner (10 Salons Completing 15-Day Cycle)',
    remainingShopsForNextMilestone: 4,
    plusOneShopStatus: 'Plus-One (+1) Shop "The Hair Sculpt Delhi" pending Day 15 qualification',
    currentEligibleReward: 'Montblanc Meisterstück Gold-Coated Pen + ₹75,000 Cash Grant',
    claimStatus: 'Eligible to Claim',
    shops: [
      {
        shopId: 'NX-SHP-002',
        shopName: 'AURA Luxury Thermal Spa',
        ownerName: 'Dr. Kabir Sethi',
        mobileNumber: '+91 98111 88392',
        address: 'Sanctuary Pavilion, Basant Lok, Vasant Vihar',
        city: 'New Delhi',
        kycStatus: 'Verified',
        qrActivationDate: '2026-08-20',
        dailyQrTransaction: 22000,
        requiredDailyQrTransaction: 1000,
        companyCommissionRate: 10,
        dailyCompanyCommission: 2200,
        dailyQualification: 'Passed',
        consecutiveQualifyingDays: 15,
        isCycleCompleted: true,
        settlementStatus: 'Settled (Bank UTR Released)',
        refundReversalStatus: 'Zero Reversals (Clean)',
        verificationStatus: 'Verified & Active',
        interiorPhoto: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=600',
        category: 'Thermal Spa & Aesthetics',
      },
      {
        shopId: 'NX-SHP-006',
        shopName: 'Amber & Pearl Bridal Sanctuary',
        ownerName: 'Simran Bajaj',
        mobileNumber: '+91 98118 77209',
        address: 'Boutique Row, Greater Kailash 2 M-Block',
        city: 'New Delhi',
        kycStatus: 'Verified',
        qrActivationDate: '2026-09-04',
        dailyQrTransaction: 16400,
        requiredDailyQrTransaction: 1000,
        companyCommissionRate: 10,
        dailyCompanyCommission: 1640,
        dailyQualification: 'Passed',
        consecutiveQualifyingDays: 15,
        isCycleCompleted: true,
        settlementStatus: 'Settled (Bank UTR Released)',
        refundReversalStatus: 'Zero Reversals (Clean)',
        verificationStatus: 'Verified & Active',
        interiorPhoto: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=600',
        category: 'Bridal Couture Artistry',
      },
      {
        shopId: 'NX-SHP-015',
        shopName: 'Sovereign Barbers of Connaught',
        ownerName: 'Gurpreet Chawla',
        mobileNumber: '+91 98114 99011',
        address: 'Inner Circle, Block F, Connaught Place',
        city: 'New Delhi',
        kycStatus: 'Verified',
        qrActivationDate: '2026-09-11',
        dailyQrTransaction: 1250,
        requiredDailyQrTransaction: 1000,
        companyCommissionRate: 10,
        dailyCompanyCommission: 125,
        dailyQualification: 'Passed',
        consecutiveQualifyingDays: 15,
        isCycleCompleted: true,
        settlementStatus: 'Settled (Bank UTR Released)',
        refundReversalStatus: 'Zero Reversals (Clean)',
        verificationStatus: 'Verified & Active',
        interiorPhoto: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&q=80&w=600',
        category: 'Heritage Barber Club',
      },
    ],
  },
];
